name: NPM Publish

on:
  push:
    branches: [deprecated]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: npm install
    - run: npm run lint
    - run: npm run build
    - run: npm deprecate dialog-redux ""
    - run: npm publish
    - run: npm deprecate dialog-redux "Use redux-dialog-wrapper instead"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
